/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lms.sheetCRUD.form.other;

import com.lms.sheetCRUD.service.BookService;
import com.lms.sheetCRUD.service.InvoiceDetailService;
import com.lms.sheetCRUD.service.InvoiceService;
import com.lms.sheetCRUD.service.SheetDetailService;
import com.lms.sheetCRUD.service.SheetService;

/**
 *
 * @author nttha
 */
public class SheetList extends javax.swing.JPanel {
    private BookService bookService;
    private SheetService sheetService;
    private SheetDetailService sheetDetailService;
    private InvoiceService invoiceService;
    private InvoiceDetailService invoiceDetailService;
    private ImportSheet importSheet;
    private ExportSheet exportSheet;

    public SheetList(BookService bookService, SheetService sheetService, SheetDetailService sheetDetailService, InvoiceService invoiceService, InvoiceDetailService invoiceDetailService) {
        initComponents();
        importSheet = new ImportSheet(bookService, sheetService, sheetDetailService);
        exportSheet = new ExportSheet(bookService, invoiceService, invoiceDetailService);
        init();
    }

    private void init() {
        tabSheet.addTab("Import List", importSheet );
        tabSheet.addTab("Export List", exportSheet);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabSheet = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 1, 40));
        jPanel11.setPreferredSize(new java.awt.Dimension(800, 60));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Sheet List");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel19Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel11.add(jPanel19, java.awt.BorderLayout.CENTER);

        add(jPanel11, java.awt.BorderLayout.PAGE_START);

        tabSheet.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 40));
        tabSheet.setPreferredSize(new java.awt.Dimension(920, 500));
        add(tabSheet, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JTabbedPane tabSheet;
    // End of variables declaration//GEN-END:variables
}
