/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lms.accountCRUD.form.other;

import java.awt.CardLayout;
import java.awt.Component;

import javax.swing.AbstractCellEditor;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JToggleButton;
import javax.swing.table.TableCellEditor;

import com.lms.accountCRUD.dal.AdminDao;
import com.lms.accountCRUD.repo.AdminRepo;
import com.lms.accountCRUD.service.AdminService;

/**
 * /**
 *
 * @author DungMinh
 */


public class ViewListAccount extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewListAccount
     */

    AdminService adminService;
    AdminDao adminDao;
    CardLayout cardLayout;
    JPanel panelParent;
    private EmployeeList employeeList;
    private AdminList adminList;

    public ViewListAccount(CardLayout cardLayout, JPanel panelParent, AdminService adminService) {

        this.cardLayout = cardLayout;
        this.panelParent = panelParent;
        adminList = new AdminList(adminService);
        employeeList = new EmployeeList(adminService);
        adminDao = new AdminRepo();
        adminService = new AdminService(adminDao);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        initComponents();
        init();
    }

    private void init() {
        tabAccount.addTab("Employee", employeeList);
        tabAccount.addTab("Admin", adminList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabAccount = new javax.swing.JTabbedPane();

        setBorder(null);

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 1, 40));
        jPanel11.setPreferredSize(new java.awt.Dimension(800, 60));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Account List");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 720, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                        jPanel19Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714,
                                                        Short.MAX_VALUE))));
        jPanel19Layout.setVerticalGroup(
                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel19Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel1)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

        jPanel11.add(jPanel19, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel11, java.awt.BorderLayout.PAGE_START);

        tabAccount.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 40));
        tabAccount.setPreferredSize(new java.awt.Dimension(920, 500));
        getContentPane().add(tabAccount, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JTabbedPane tabAccount;
    // End of variables declaration//GEN-END:variables
}
