/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lms.informationCRUD.form.other;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;

import com.lms.auth.controller.BCrypt;
import com.lms.informationCRUD.entities.Employee;
import com.lms.auth.entities.User;
import com.lms.informationCRUD.entities.Admin;
import com.lms.informationCRUD.service.InfoService;

/**
 *
 * @author nttha
 */
public class ViewInformation extends javax.swing.JPanel {

        User accCur;
        String role;
        InfoService infoService;

        public ViewInformation(User accCur, String role, InfoService infoService) throws ParseException {
                this.accCur = accCur;
                this.role = role;
                this.infoService = infoService;
                initComponents();
                tenTaiKhoan.setText(accCur.getName());
                phoneNum.setText(accCur.getPhoneNumber());
                if (accCur.getDob() != null) {
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                        Date date = sdf.parse(accCur.getDob());
                        jDateChooser3.setDate(date);
                }
                genderChoose.setSelectedItem(accCur.getGender());
                System.out.println("babds" + accCur.toString());

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel11 = new javax.swing.JPanel();
                jPanel19 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                tabAccount = new javax.swing.JTabbedPane();
                jPanel1 = new javax.swing.JPanel();
                panel = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                tenTaiKhoan = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                phoneNum = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                jLabel7 = new javax.swing.JLabel();
                jDateChooser3 = new com.toedter.calendar.JDateChooser();
                genderChoose = new javax.swing.JComboBox<>();
                jLabel8 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                panel2 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                passCom = new javax.swing.JPasswordField();
                passCur = new javax.swing.JPasswordField();
                passAft = new javax.swing.JPasswordField();
                jButton2 = new javax.swing.JButton();
                passCurEr = new javax.swing.JLabel();
                passAftEr = new javax.swing.JLabel();
                passComEr = new javax.swing.JLabel();

                setLayout(new java.awt.BorderLayout());

                jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 1, 40));
                jPanel11.setPreferredSize(new java.awt.Dimension(800, 60));
                jPanel11.setLayout(new java.awt.BorderLayout());

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabel1.setText("Information");

                javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
                jPanel19.setLayout(jPanel19Layout);
                jPanel19Layout.setHorizontalGroup(
                                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 720, Short.MAX_VALUE)
                                                .addGroup(jPanel19Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel19Layout.createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                714,
                                                                                                                Short.MAX_VALUE))));
                jPanel19Layout.setVerticalGroup(
                                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 68, Short.MAX_VALUE)
                                                .addGroup(jPanel19Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel19Layout.createSequentialGroup()
                                                                                .addGap(14, 14, 14)
                                                                                .addComponent(jLabel1)
                                                                                .addContainerGap(
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))));

                jPanel11.add(jPanel19, java.awt.BorderLayout.CENTER);

                add(jPanel11, java.awt.BorderLayout.PAGE_START);

                tabAccount.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 40));
                tabAccount.setPreferredSize(new java.awt.Dimension(920, 500));

                jPanel1.setBackground(new java.awt.Color(204, 204, 255));
                jPanel1.setPreferredSize(new java.awt.Dimension(720, 400));

                panel.setBackground(new java.awt.Color(255, 255, 255));

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel2.setText("Full name");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel3.setText("Phone Number");

                jButton1.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
                jButton1.setText("Save");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel7.setText("Date");

                jDateChooser3.setPreferredSize(new java.awt.Dimension(64, 40));

                genderChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
                genderChoose.setPreferredSize(new java.awt.Dimension(72, 40));

                jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel8.setText("Gender");

                javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
                panel.setLayout(panelLayout);
                panelLayout.setHorizontalGroup(
                                panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelLayout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addGroup(panelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(tenTaiKhoan,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                336,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(phoneNum)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                98,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(panelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(panelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jDateChooser3,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                160,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel7,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                56,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(panelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel8,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                56,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(genderChoose,
                                                                                                                                0,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)))
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                89,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(34, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                158,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(121, 121, 121)));
                panelLayout.setVerticalGroup(
                                panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelLayout.createSequentialGroup()
                                                                .addGap(33, 33, 33)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tenTaiKhoan,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(phoneNum,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(21, 21, 21)
                                                                .addGroup(panelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(jLabel8))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(panelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jDateChooser3,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(genderChoose,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                41,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                43,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(41, Short.MAX_VALUE)));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 720, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(0, 159, Short.MAX_VALUE)
                                                                                .addComponent(panel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 159, Short.MAX_VALUE))));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 443, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(panel,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))));

                tabAccount.addTab("Information", jPanel1);

                jPanel2.setBackground(new java.awt.Color(204, 204, 255));

                panel2.setBackground(new java.awt.Color(255, 255, 255));

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel4.setText("Current Pw");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel5.setText("New Pw");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel6.setText("Verify New Pw");

                jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jButton2.setText("Save");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                passCurEr.setForeground(new java.awt.Color(255, 51, 102));

                passAftEr.setForeground(new java.awt.Color(255, 51, 102));

                passComEr.setForeground(new java.awt.Color(255, 51, 102));

                javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
                panel2.setLayout(panel2Layout);
                panel2Layout.setHorizontalGroup(
                                panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panel2Layout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addGroup(panel2Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(passCom,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                321,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(passAft)
                                                                                .addComponent(passCur)
                                                                                .addComponent(passCurEr,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(passAftEr,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(passComEr,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                panel2Layout.createSequentialGroup()
                                                                                                                .addComponent(jButton2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                154,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(78, 78, 78)))
                                                                .addContainerGap(49, Short.MAX_VALUE)));
                panel2Layout.setVerticalGroup(
                                panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panel2Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passCur,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(passCurEr)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passAft,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passAftEr)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passCom,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passComEr)
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jButton2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                36,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(68, Short.MAX_VALUE)));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 720, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(panel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 443, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(panel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))));

                tabAccount.addTab("Change Password", jPanel2);

                add(tabAccount, java.awt.BorderLayout.CENTER);
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                String fullName = tenTaiKhoan.getText();
                String contactNumberPhone = phoneNum.getText();
                String gender = genderChoose.getSelectedItem().toString();
                String date = "";
                if (jDateChooser3.getDate() != null) {
                        date = jDateChooser3.getDate().toString();
                }
                if (fullName.equals("") || contactNumberPhone.equals("") || gender.equals("") || date.equals("")) {
                        JOptionPane.showMessageDialog(this, "please full fill !");
                } else {
                        if (role == "Admin") {
                                Admin admin = new Admin();
                                admin = infoService.getAdminById(accCur.getId());

                                if (infoService.getAdminByPhoneNumber(contactNumberPhone).getAdminId() != null) {
                                        JOptionPane.showMessageDialog(this, "Phone number already exists !",
                                                        "Warning",
                                                        JOptionPane.WARNING_MESSAGE);
                                        return;
                                }
                                if (infoService.getAdminById(accCur.getId()) != null) {
                                        infoService.editAccount(contactNumberPhone, admin.getPwd(), fullName, date,
                                                        gender, "Admin");
                                        JOptionPane.showMessageDialog(this, "Edit Successfull !");
                                } else {
                                        JOptionPane.showMessageDialog(this, "Something went wrong !", "Warning",
                                                        JOptionPane.WARNING_MESSAGE);
                                }

                        }
                        if (role == "Employee") {
                                Employee employee = new Employee();
                                employee = infoService.getEmployeeById(accCur.getId());
                                if (infoService.getEmployeeByPhoneNumber(contactNumberPhone).getEmpId() != null) {
                                        JOptionPane.showMessageDialog(this, "Phone number already exists !",
                                                        "Warning",
                                                        JOptionPane.WARNING_MESSAGE);
                                        return;
                                }
                                if (infoService.getEmployeeById(accCur.getId()) != null) {
                                        infoService.editAccount(contactNumberPhone, employee.getPwd(), fullName, date,
                                                        gender, "Employee");
                                        JOptionPane.showMessageDialog(this, "Edit Successfull !");
                                } else {
                                        JOptionPane.showMessageDialog(this, "Something went wrong !", "Warning",
                                                        JOptionPane.WARNING_MESSAGE);
                                }
                        }
                }
        }// GEN-LAST:event_jButton1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
                boolean check = true;
                String curPass = passCur.getText();
                String newPass = passAft.getText();
                String newPassConf = passCom.getText();

                if (curPass.length() == 0) {
                        check = false;
                        passCurEr.setText("Enter current Pw");
                } else {
                        passCurEr.setText("");
                }
                if (newPass.length() == 0) {
                        check = false;
                        passAftEr.setText("Enter new PWD");
                } else {
                        passAftEr.setText("");
                }
                if (newPassConf.length() == 0) {
                        check = false;
                        passComEr.setText("Verify new PWD");
                } else {
                        passComEr.setText("");
                }
                if (check == true) {
                        if (role == "Admin") {
                                Admin admin = new Admin();
                                admin = infoService.getAdminById(accCur.getId());
                                if (BCrypt.checkpw(curPass, admin.getPwd())) {
                                        if (newPass.equals(newPassConf)) {
                                                infoService.editAccount(admin.getPhoneNumber(), newPass,
                                                                admin.getName(),
                                                                admin.getDob(), admin.getGender(), "Admin");
                                                JOptionPane.showMessageDialog(this, "Edit Successfull !");
                                        } else {
                                                JOptionPane.showMessageDialog(this,
                                                                "New password and confirm password do not match !",
                                                                "Warning", JOptionPane.WARNING_MESSAGE);
                                        }
                                } else {
                                        JOptionPane.showMessageDialog(this, "Current password is incorrect !",
                                                        "Warning",
                                                        JOptionPane.WARNING_MESSAGE);
                                }
                        }
                        if (role == "Employee") {
                                Employee employee = new Employee();
                                employee = infoService.getEmployeeById(accCur.getId());
                                if (BCrypt.checkpw(curPass, employee.getPwd())) {
                                        if (newPass.equals(newPassConf)) {
                                                infoService.editAccount(employee.getPhoneNumber(), newPass,
                                                                employee.getName(),
                                                                employee.getDob(), employee.getGender(), "Employee");
                                                JOptionPane.showMessageDialog(this, "Edit Successfull !");
                                        } else {
                                                JOptionPane.showMessageDialog(this,
                                                                "New password and confirm password do not match !",
                                                                "Warning", JOptionPane.WARNING_MESSAGE);
                                        }
                                } else {
                                        JOptionPane.showMessageDialog(this, "Current password is incorrect !",
                                                        "Warning",
                                                        JOptionPane.WARNING_MESSAGE);
                                }
                        }
                }
        }// GEN-LAST:event_jButton2ActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox<String> genderChoose;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private com.toedter.calendar.JDateChooser jDateChooser3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel19;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel panel;
        private javax.swing.JPanel panel2;
        private javax.swing.JPasswordField passAft;
        private javax.swing.JLabel passAftEr;
        private javax.swing.JPasswordField passCom;
        private javax.swing.JLabel passComEr;
        private javax.swing.JPasswordField passCur;
        private javax.swing.JLabel passCurEr;
        private javax.swing.JTextField phoneNum;
        private javax.swing.JTabbedPane tabAccount;
        private javax.swing.JTextField tenTaiKhoan;
        // End of variables declaration//GEN-END:variables
}
