package com.lms.auth.form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.Timer;

import com.formdev.flatlaf.FlatClientProperties;
import com.lms.auth.entities.User;
import com.lms.auth.service.AuthService;
import com.lms.dashboard.application.Application;

// import raven.toast.Notifications;

public class Login extends javax.swing.JPanel {
    private AuthService authService;

    public Login(AuthService authService) {
        initComponents();
        this.authService = authService;

        txtPhoneNumber.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter your phone number");
        txtPass.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter your password");
        selectionRole.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Select your role");

        txtPass.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
        txtPass.putClientProperty(FlatClientProperties.STYLE, "showRevealButton: true; showClearButton: true;");
        txtPass.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
        txtPass.putClientProperty(FlatClientProperties.STYLE, "showRevealButton: true; showClearButton: true;");

    }

    public Login(AuthService authService, String phoneNumber, String pwd, String role) {

        System.out.println(phoneNumber + " " + pwd + " " + role);
        initComponents();
        this.authService = authService;
        txtPhoneNumber.setText(phoneNumber);
        txtPass.setText(pwd);
        selectionRole.setSelectedItem(role);
        signIn(authService, phoneNumber, pwd, role);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        signInLabel = new javax.swing.JLabel();
        signUpLabel = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();
        forgotPwButton = new javax.swing.JButton();
        rememberCheckbok = new javax.swing.JCheckBox();
        txtPhoneNumber = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        selectionRole = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        phoneLable = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();
        errorPhone = new javax.swing.JLabel();
        errorPass = new javax.swing.JLabel();
        errorRole = new javax.swing.JLabel();

        signInLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        signInLabel.setText("Sign In");

        signUpLabel.setText("Don't have a account ?");

        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        forgotPwButton.setText("Forgot Password");
        forgotPwButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPwButtonActionPerformed(evt);
            }
        });

        rememberCheckbok.setText("Remember me");
        rememberCheckbok.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rememberCheckbok.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rememberCheckbok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberCheckbokActionPerformed(evt);
            }
        });

        selectionRole.setEditable(true);
        selectionRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee" }));
        selectionRole.setSelectedIndex(-1);

        phoneLable.setText("Phone Number");

        passLabel.setText("Password");

        roleLabel.setText("Role");

        signInButton.setBackground(new java.awt.Color(64, 68, 237));
        signInButton.setForeground(new java.awt.Color(255, 255, 255));
        signInButton.setText("Sign In");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        errorPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        errorPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        errorRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addComponent(rememberCheckbok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(forgotPwButton))
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(signInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLoginLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(signUpLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(signUpButton)))
                                .addGap(0, 63, Short.MAX_VALUE))))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(phoneLable, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorRole, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectionRole, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(signInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLable, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(errorPass))
                .addGap(7, 7, 7)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleLabel)
                    .addComponent(errorRole))
                .addGap(4, 4, 4)
                .addComponent(selectionRole, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forgotPwButton)
                    .addComponent(rememberCheckbok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpLabel)
                    .addComponent(signUpButton))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 329, Short.MAX_VALUE)
                    .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 329, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rememberCheckbokActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rememberCheckbokActionPerformed
        if (rememberCheckbok.isSelected()) {
            // Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER,
            //         "Remember me is on");

        } else {
            // Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER,
            //         "Remember me is off");
        }
    }// GEN-LAST:event_rememberCheckbokActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_signInButtonActionPerformed
        String user = txtPhoneNumber.getText().trim();
        String pass = String.valueOf(txtPass.getPassword());
        String role = "";
        if (selectionRole.getSelectedItem() != null) {
            role = selectionRole.getSelectedItem().toString();
        }
        boolean action = true;

        if (user.equals("")) {
            errorPhone.setText("Please input user phone number");
            errorPhone.setForeground(new java.awt.Color(255, 0, 0));
            txtPhoneNumber.grabFocus();
            action = false;
        }
        if (pass.equals("")) {
            errorPass.setText("Please input password");
            errorPass.setForeground(new java.awt.Color(255, 0, 0));
            if (action) {
                txtPass.grabFocus();
            }
            action = false;
        }
        if (role.equals("") || role == null || !role.equals("Admin") && !role.equals("Employee")) {
            System.out.println(role);
            errorRole.setText("Please select role");
            errorRole.setForeground(new java.awt.Color(255, 0, 0));
            if (action) {
                txtPass.grabFocus();
            }
            action = false;
        }
        if (!user.equals("")) {
            errorPhone.setText("");
        }
        if (!pass.equals("")) {
            errorPass.setText("");
        }
        if (role.equals("Admin") || role.equals("Employee")) {
            errorRole.setText("");
        }

        System.out.println(user + " " + pass + " " + role);

        if (action) {
            signIn(authService, user, pass, role);
        }
    }// GEN-LAST:event_signInButtonActionPerformed

    private void signIn(AuthService authService, String user, String pass, String role) {

        User userLogin = authService.logIn(user, pass, role);
        if (userLogin.getName() != null) {
            // System.out.print(userLogin.getName());
            if (rememberCheckbok.isSelected()) {
                try {
                    FileWriter writer = new FileWriter("login.txt", false);
                    writer.write(user + "\n" + pass + "\n" + role);
                    writer.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            // Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER,
            //         "Login Success\n" + " Welcome " + userLogin.getName());
            final String finalRole = role;
            Timer timer = new Timer(3000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    ((Timer) e.getSource()).stop(); // Stop the timer
                    if (finalRole.equals("Admin")) {
                        Application.dashboardAdmin();
                        Application.setUserInformation(userLogin);
                        txtPhoneNumber.setText("");
                        txtPass.setText("");
                        selectionRole.setSelectedIndex(-1);
                    } else if (finalRole.equals("Employee")) {
                        Application.dashboardUser();
                        Application.setUserInformation(userLogin);
                        txtPhoneNumber.setText("");
                        txtPass.setText("");
                        selectionRole.setSelectedIndex(-1);
                    }
                }
            });
            timer.setRepeats(false); // Ensure the timer only runs once
            timer.start();

        } else {
            // Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER,
            //         "Login Failed\n" + "User does not exist or password is incorrect");
            errorPhone.setText("User does not exist");
            errorPhone.setForeground(new java.awt.Color(255, 0, 0));
            txtPhoneNumber.grabFocus();
        }
    }

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_signUpButtonActionPerformed
        Application.signUp();
    }// GEN-LAST:event_signUpButtonActionPerformed

    private void forgotPwButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_forgotPwButtonActionPerformed
        Application.resetPw();
    }// GEN-LAST:event_forgotPwButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorPass;
    private javax.swing.JLabel errorPhone;
    private javax.swing.JLabel errorRole;
    private javax.swing.JButton forgotPwButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel phoneLable;
    private javax.swing.JCheckBox rememberCheckbok;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JComboBox<String> selectionRole;
    private javax.swing.JButton signInButton;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
