/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lms.bookCRUD.form.other;

import java.awt.CardLayout;
import java.awt.Component;

import javax.swing.AbstractCellEditor;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

import com.lms.bookCRUD.dal.AuthorDao;
import com.lms.bookCRUD.dal.BookAuthorDao;
import com.lms.bookCRUD.dal.BookCategoryDao;
import com.lms.bookCRUD.dal.BookDao;
import com.lms.bookCRUD.dal.CategoryDao;
import com.lms.bookCRUD.dal.PublisherDao;
import com.lms.bookCRUD.form.BookView;
import com.lms.bookCRUD.repo.AuthorRepo;
import com.lms.bookCRUD.repo.BookAuthorRepo;
import com.lms.bookCRUD.repo.BookCategoryRepo;
import com.lms.bookCRUD.repo.BookRepo;
import com.lms.bookCRUD.repo.CategoryRepo;
import com.lms.bookCRUD.repo.PublisherRepo;
import com.lms.bookCRUD.service.BookService;

public class ListBooks extends javax.swing.JPanel {
    private BookDao bookDao;
    private AuthorDao authorDao;
    private CategoryDao categoryDao;
    private PublisherDao publisherDao;
    private BookAuthorDao bookAuthorDao;
    private BookCategoryDao bookCategoryDao;
    private BookService bookService;
    private CardLayout cardLayout;
    private JPanel parentPanel;
    private AllBook allBook;
    private UnavailableBook unavailableBook;
    private AvailableBook availableBook;

    public ListBooks(CardLayout cardLayout, JPanel parentPanel, BookService bookService) {
        this.cardLayout = cardLayout;
        this.parentPanel = parentPanel;
        allBook = new AllBook(bookService);
        unavailableBook = new UnavailableBook(bookService);
        availableBook = new AvailableBook(bookService);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void init() {
        tabBook.addTab("Available",availableBook);
        tabBook.addTab("Unavailable",unavailableBook);
        tabBook.addTab("All",allBook);
    }


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabBook = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 40, 1, 40));
        jPanel11.setPreferredSize(new java.awt.Dimension(800, 60));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Book List");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel19Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel11.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel11);

        add(jPanel9, java.awt.BorderLayout.NORTH);

        tabBook.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 1, 40));
        add(tabBook, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerforme
        cardLayout.show(parentPanel, "addBook");
    }// GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane tabBook;
    // End of variables declaration//GEN-END:variables
}
