/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lms.bookCRUD.form.other;

import java.awt.Color;
import java.awt.Font;
import java.util.List;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.lms.bookCRUD.model.BookModel;
import com.lms.bookCRUD.service.BookService;
import com.lms.bookCRUD.ui.CenterTableCellRenderer;

public class UnavailableBook extends javax.swing.JPanel {
    private BookService bookService;

    public UnavailableBook(BookService bookService) {
        this.bookService = bookService;
        initComponents();
        init();
    }

    private void init() {
        searchField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Search...");
        searchBookButton.setIcon(new FlatSVGIcon("svg/search.svg"));
        filterBookButton.setIcon(new FlatSVGIcon("svg/filter.svg"));

        List<BookModel> bookModels = bookService.getUnavailableBooks();
        DefaultTableModel tblModel = (DefaultTableModel) bookList.getModel();
        reloadTable(tblModel, bookModels);

        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(bookList.getModel());
        bookList.setRowSorter(sorter);

    }

    public void reloadTable(DefaultTableModel tblModel, List<BookModel> bookModels) {
        CenterTableCellRenderer centerRenderer = new CenterTableCellRenderer();
        customTable(bookList);
        int idx = 0;
        tblModel.setColumnIdentifiers(new Object[] { "No.", "ID", "Title", "Edition", "Categories", "Authors",
                "Publisher", "Sale Price", "Quantity" });
        for (BookModel bookModel : bookModels) {
            tblModel.addRow(new Object[] { ++idx, bookModel.getId(), bookModel.getTitle(), bookModel.getEdition(),
                    bookModel.getCategoriesString(),
                    bookModel.getAuthorsString(), bookModel.getPublisher().toString(),
                    bookModel.getSalePrice(), bookModel.getQuantity() });
        }

        bookList.getColumnModel().getColumn(0).setPreferredWidth(20);

        for (int columnIndex = 0; columnIndex < bookList.getColumnCount(); columnIndex++) {
            bookList.getColumnModel().getColumn(columnIndex).setCellRenderer(centerRenderer);
        }

        bookList.setModel(tblModel);
        // bookList.getColumnModel().getColumn(8).setCellRenderer(new ToggleRenderer());
        // bookList.getColumnModel().getColumn(8).setCellEditor(new ToggleEditor());
        // bookList.getColumnModel().getColumn(9).setCellRenderer(new
        // EditToggleRenderer());
        // bookList.getColumnModel().getColumn(9).setCellEditor(new EditToggleEditor());

    }

    private void customTable(javax.swing.JTable table) {
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        table.getTableHeader().setBackground(new Color(125, 200, 204));
        table.getTableHeader().setForeground(new Color(0, 0, 0));
        table.setRowHeight(30);
        table.setShowGrid(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        filterBookButton = new javax.swing.JButton();
        filterSearch = new javax.swing.JComboBox<>();
        jPanel21 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        searchBookButton = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        bookList = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 10, 60));
        setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(800, 100));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Unavailable Books");
        jPanel17.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel17);

        jPanel3.setPreferredSize(new java.awt.Dimension(800, 40));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel18.setPreferredSize(new java.awt.Dimension(150, 40));

        filterBookButton.setPreferredSize(new java.awt.Dimension(40, 40));
        filterBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBookButtonActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(filterBookButton);

        filterSearch.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filterSearch.setPreferredSize(new java.awt.Dimension(100, 40));
        filterSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterSearchActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(filterSearch);

        jPanel18.add(jSplitPane1);

        jPanel3.add(jPanel18, java.awt.BorderLayout.WEST);

        jPanel21.setPreferredSize(new java.awt.Dimension(700, 40));

        searchField.setPreferredSize(new java.awt.Dimension(71, 40));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel21Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                                .addGap(8, 8, 8)));
        jPanel21Layout.setVerticalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel21Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(11, Short.MAX_VALUE)));

        jPanel3.add(jPanel21, java.awt.BorderLayout.CENTER);

        jPanel22.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel22.setRequestFocusEnabled(false);

        searchBookButton.setPreferredSize(new java.awt.Dimension(60, 40));
        searchBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookButtonActionPerformed(evt);
            }
        });
        jPanel22.add(searchBookButton);

        jPanel3.add(jPanel22, java.awt.BorderLayout.EAST);

        jPanel13.add(jPanel3);

        add(jPanel13, java.awt.BorderLayout.NORTH);

        jPanel23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 40, 1));
        jPanel23.setPreferredSize(new java.awt.Dimension(800, 400));

        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 5));

        bookList.setRowHeight(30);
        bookList.setShowGrid(true);
        jScrollPane5.setViewportView(bookList);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
                jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 561, Short.MAX_VALUE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 561,
                                        Short.MAX_VALUE)));
        jPanel23Layout.setVerticalGroup(
                jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 253, Short.MAX_VALUE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)));

        add(jPanel23, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void filterBookButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_filterBookButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_filterBookButtonActionPerformed

    private void filterSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_filterSearchActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_filterSearchActionPerformed

    private void searchBookButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchBookButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_searchBookButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookList;
    private javax.swing.JButton filterBookButton;
    private javax.swing.JComboBox<String> filterSearch;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton searchBookButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
