/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lms.authorCRUD;

import java.awt.CardLayout;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.lms.authorCRUD.dal.AuthorDao;
import com.lms.authorCRUD.entities.Author;
import com.lms.authorCRUD.repo.AuthorRepo;
import com.lms.authorCRUD.service.AuthorService;

/**
 *
 * @author Van Vinh
 */
public class EditInfoAuthorPanel extends javax.swing.JPanel {

        /**
         * Creates new form NewPublisher
         */
        public EditInfoAuthorPanel(CardLayout cobj, JPanel panelParent, Author author) {
                this.dataAuthor = author;
                this.panelParent = panelParent;
                this.cardLayout = cobj;
                this.empDao = new AuthorRepo();
                this.empService = new AuthorService(empDao);
                initComponents();
        }

        public void setDataAuthor(Author author) {
                this.dataAuthor = author;
        }

        public String toString() {
                return dataAuthor.toString();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        public void initComponents() {
                pageLabel = new javax.swing.JLabel();
                id = new javax.swing.JTextField();
                status = new javax.swing.JComboBox<>();
                idLabel = new javax.swing.JLabel();
                genderLabel = new javax.swing.JLabel();
                statusLabel = new javax.swing.JLabel();
                cancelBtn = new javax.swing.JButton();
                saveBtn = new javax.swing.JButton();
                name = new javax.swing.JTextField();
                nameLabel = new javax.swing.JLabel();
                gender = new javax.swing.JComboBox<>();
                imageAvatar = new com.lms.custom.ImageAvatar();

                pageLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                pageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                pageLabel.setText("Edit info author ");

                id.setEditable(false);
                id.setText(dataAuthor != null ? dataAuthor.getAuthorId() : "");

                status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hide", "UnHide" }));
                status.setSelectedItem(dataAuthor.isHide() == true ? "Hide" : "UnHide");

                idLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                idLabel.setLabelFor(id);
                idLabel.setText("Author Id");

                genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                genderLabel.setLabelFor(gender);
                genderLabel.setText("Gender");

                statusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                statusLabel.setLabelFor(status);
                statusLabel.setText("Hide/UnHide");

                cancelBtn.setForeground(new java.awt.Color(255, 140, 56));
                cancelBtn.setText("Cancel");
                cancelBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 122, 7), 2, true));
                cancelBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelBtnActionPerformed(evt);
                        }
                });

                saveBtn.setBackground(new java.awt.Color(255, 122, 7));
                saveBtn.setForeground(new java.awt.Color(255, 255, 255));
                saveBtn.setText("Save");
                saveBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveBtnActionPerformed(evt);
                        }
                });

                name.setText(dataAuthor.getAuthorName() == null ? "" : dataAuthor.getAuthorName());

                nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                nameLabel.setLabelFor(id);
                nameLabel.setText("Author Name");

                gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
                gender.setSelectedItem(dataAuthor.getAuthorGender().equals("male") ? "Male" : "Female");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(this);
                setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(307, 307, 307)
                                                                                                .addComponent(cancelBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                100,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(29, 29, 29)
                                                                                                .addComponent(saveBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                100,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(146, 146, 146)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(idLabel,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                122,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(genderLabel,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                96,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(gender,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                250,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGap(60, 60, 60)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(status,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                250,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(statusLabel,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                109,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addComponent(id,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                560,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(name,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                560,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(nameLabel,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                122,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(117, 117,
                                                                                                                                                117)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(imageAvatar,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                134,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(pageLabel))))))
                                                                .addContainerGap(94, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(71, 71, 71)
                                                                .addComponent(pageLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(imageAvatar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                95,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(56, 56, 56)
                                                                .addComponent(idLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(id,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                34,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                31,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(nameLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(name,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                34,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(genderLabel)
                                                                                .addComponent(statusLabel))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(status,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                35,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(gender,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                35,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(37, 37, 37)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(cancelBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                31,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(saveBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                31,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(149, 149, 149)));
        }// </editor-fold>//GEN-END:initComponents

        private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelBtnActionPerformed
                // TODO add your handling code here:
                cardLayout.show(panelParent, "authorsPage");
        }// GEN-LAST:event_cancelBtnActionPerformed

        private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveBtnActionPerformed
                // TODO add your handling code here:
                String id = this.id.getText();
                String name = this.name.getText();
                String gender = (String) this.gender.getSelectedItem();
                String status = (String) this.status.getSelectedItem();

                if (name.equals("") || gender.equals("") || status.equals("")) {
                        JOptionPane.showMessageDialog(null, "Please fill all the fields");
                } else {
                        empService.editInfo(id, name, gender, status);
                }
        }// GEN-LAST:event_saveBtnActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        CardLayout cardLayout;
        JPanel panelParent;
        AuthorService empService;
        AuthorDao empDao;

        private javax.swing.JComboBox<String> status;
        private javax.swing.JComboBox<String> gender;
        private com.lms.custom.ImageAvatar imageAvatar;
        private javax.swing.JButton cancelBtn;
        private javax.swing.JButton saveBtn;
        private javax.swing.JLabel pageLabel;
        private javax.swing.JLabel idLabel;
        private javax.swing.JLabel genderLabel;
        private javax.swing.JLabel statusLabel;
        private javax.swing.JLabel nameLabel;
        private javax.swing.JTextField id;
        private javax.swing.JTextField name;
        private Author dataAuthor;
        // End of variables declaration//GEN-END:variables
}
