/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lms.dataSaleCRUD;

import java.awt.Color;

import com.lms.dataSaleCRUD.component.chart.ModelChart;

/**
 *
 * @author PC
 */
public class viewDataSalePanel extends javax.swing.JPanel {

    /**
     * Creates new form viewDataSalePanel
     */
    public viewDataSalePanel() {
        initComponents();
        chart1.addLegend("Income", new Color(255, 0, 77));
        chart1.addData(new ModelChart("Jan", new double[]{500}));
        chart1.addData(new ModelChart("Feb", new double[]{500}));
        chart1.addData(new ModelChart("Mar", new double[]{500}));
        chart1.addData(new ModelChart("Apr", new double[]{580}));
        chart1.addData(new ModelChart("May", new double[]{550}));
        chart1.addData(new ModelChart("June", new double[]{590}));

        chart2.addLegend("Income", new Color(245, 189, 135));
        chart2.addData(new ModelChart("Jan", new double[]{500}));
        chart2.addData(new ModelChart("Feb", new double[]{600}));
        chart2.addData(new ModelChart("Mar", new double[]{200}));
        chart2.addData(new ModelChart("Apr", new double[]{480}));
        chart2.addData(new ModelChart("May", new double[]{350}));
        chart2.addData(new ModelChart("June", new double[]{190}));

        chart3.addLegend("Income", new Color(245, 189, 135));
        chart3.addData(new ModelChart("Jan", new double[]{500}));
        chart3.addData(new ModelChart("Feb", new double[]{600}));
        chart3.addData(new ModelChart("Mar", new double[]{200}));
        chart3.addData(new ModelChart("Apr", new double[]{480}));
        chart3.addData(new ModelChart("May", new double[]{350}));
        chart3.addData(new ModelChart("June", new double[]{190}));

        chart4.addLegend("Income", new Color(245, 189, 135));
        chart4.addData(new ModelChart("Jan", new double[]{500}));
        chart4.addData(new ModelChart("Feb", new double[]{600}));
        chart4.addData(new ModelChart("Mar", new double[]{200}));
        chart4.addData(new ModelChart("Apr", new double[]{480}));
        chart4.addData(new ModelChart("May", new double[]{300}));
        chart4.addData(new ModelChart("June", new double[]{190}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart2 = new com.lms.dataSaleCRUD.component.chart.Chart();
        btn4 = new com.lms.dataSaleCRUD.ui.Button();
        btn3 = new com.lms.dataSaleCRUD.ui.Button();
        btn2 = new com.lms.dataSaleCRUD.ui.Button();
        btn1 = new com.lms.dataSaleCRUD.ui.Button();
        chart1 = new com.lms.dataSaleCRUD.component.chart.Chart();
        chart4 = new com.lms.dataSaleCRUD.component.chart.Chart();
        chart3 = new com.lms.dataSaleCRUD.component.chart.Chart();

        btn4.setBackground(new java.awt.Color(60, 58, 72));
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setLabel("View data sale - Customer");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(60, 58, 72));
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setLabel("View data sale - Category");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(60, 58, 72));
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setLabel("View data sale - Employee");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(60, 58, 72));
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setLabel("View data sale - Book");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chart3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chart4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chart4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(chart3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        viewDataSaleCustomer viewCustomer = new viewDataSaleCustomer();
        viewCustomer.setVisible(true);
        viewCustomer.pack();
        viewCustomer.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        viewDataSaleCategory viewCategory = new viewDataSaleCategory();
        viewCategory.setVisible(true);
        viewCategory.pack();
        viewCategory.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        viewDataSaleEmployee viewEmployee = new viewDataSaleEmployee();
        viewEmployee.setVisible(true);
        viewEmployee.pack();
        viewEmployee.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        viewDataSaleBook viewBook = new viewDataSaleBook();
        viewBook.setVisible(true);
        viewBook.pack();
        viewBook.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.lms.dataSaleCRUD.ui.Button btn1;
    private com.lms.dataSaleCRUD.ui.Button btn2;
    private com.lms.dataSaleCRUD.ui.Button btn3;
    private com.lms.dataSaleCRUD.ui.Button btn4;
    private com.lms.dataSaleCRUD.component.chart.Chart chart1;
    private com.lms.dataSaleCRUD.component.chart.Chart chart2;
    private com.lms.dataSaleCRUD.component.chart.Chart chart3;
    private com.lms.dataSaleCRUD.component.chart.Chart chart4;
    // End of variables declaration//GEN-END:variables
}
